In [1]:
import pandas as pd

PATH = "COVID-19-master\csse_covid_19_data\csse_covid_19_daily_reports/"

doc = pd.read_csv(f"{PATH}04-01-2020.csv", encoding="utf-8-sig")

In [3]:
doc.head()

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
0,45001.0,Abbeville,South Carolina,US,2020-04-01 21:58:49,34.223334,-82.461707,4,0,0,4,"Abbeville, South Carolina, US"
1,22001.0,Acadia,Louisiana,US,2020-04-01 21:58:49,30.295065,-92.414197,47,1,0,46,"Acadia, Louisiana, US"
2,51001.0,Accomack,Virginia,US,2020-04-01 21:58:49,37.767072,-75.632346,7,0,0,7,"Accomack, Virginia, US"
3,16001.0,Ada,Idaho,US,2020-04-01 21:58:49,43.452658,-116.241552,195,3,0,192,"Ada, Idaho, US"
4,19001.0,Adair,Iowa,US,2020-04-01 21:58:49,41.330756,-94.471059,1,0,0,1,"Adair, Iowa, US"

In [4]:
# 왜 국가에서부터 데이터를 보려고 하는가?
# 국가 별 코로나 발병 추이를 보고 싶어! 국가라는 기준이 중요하다! 그래서 국가에 대한 부분을 먼저 보려고 해!

countries = doc["Country_Region"]
countries.head()

0    US
1    US
2    US
3    US
4    US
Name: Country_Region, dtype: object

In [6]:
print(countries.size, countries.count())
# 해당 데이터 프레임의 전체 행의 갯수가 2522개! # 결측치를 제거한 실제 값, 유효한 값이 들어가져 있는 갯수!
# 얼마만큼의 오차가 있는지 보기 위해서!
# 2522 행의 2522개의 값이 모두 있네! 값이 누락된 것은 없는 것으로 판단!

2522 2522

In [12]:
# 몇 개의 나라가 있는가 확인하고 싶어! 결측이 없다는 건 확인했으니까 제거는 필요 없을 것 같고
# 유니크한 형태의 값으로 보고 싶어!
countries.unique()

# 몇 개국일까?
print(countries.unique(), len(countries.unique()))
# 전체 행 갯수 = 2522개, 실제 집계된 국가 수 = 190개

['US' 'Canada' 'United Kingdom' 'China' 'Netherlands' 'Australia'
 'Denmark' 'France' 'Afghanistan' 'Albania' 'Algeria' 'Andorra' 'Angola'
 'Antigua and Barbuda' 'Argentina' 'Armenia' 'Austria' 'Azerbaijan'
 'Bahamas' 'Bahrain' 'Bangladesh' 'Barbados' 'Belarus' 'Belgium' 'Belize'
 'Benin' 'Bhutan' 'Bolivia' 'Bosnia and Herzegovina' 'Botswana' 'Brazil'
 'Brunei' 'Bulgaria' 'Burkina Faso' 'Burma' 'Burundi' 'Cabo Verde'
 'Cambodia' 'Cameroon' 'Central African Republic' 'Chad' 'Chile'
 'Colombia' 'Congo (Brazzaville)' 'Congo (Kinshasa)' 'Costa Rica'
 "Cote d'Ivoire" 'Croatia' 'Cuba' 'Cyprus' 'Czechia' 'Diamond Princess'
 'Djibouti' 'Dominica' 'Dominican Republic' 'Ecuador' 'Egypt'
 'El Salvador' 'Equatorial Guinea' 'Eritrea' 'Estonia' 'Eswatini'
 'Ethiopia' 'Fiji' 'Finland' 'Gabon' 'Gambia' 'Georgia' 'Germany' 'Ghana'
 'Greece' 'Grenada' 'Guatemala' 'Guinea' 'Guinea-Bissau' 'Guyana' 'Haiti'
 'Holy See' 'Honduras' 'Hungary' 'Iceland' 'India' 'Indonesia' 'Iran'
 'Iraq' 'Ireland' 'Israel' 'Italy' 'Jamaica' 'Japan' 'Jordan' 'Kazakhstan'
 'Kenya' 'Korea, South' 'Kosovo' 'Kuwait' 'Kyrgyzstan' 'Laos' 'Latvia'
 'Lebanon' 'Liberia' 'Libya' 'Liechtenstein' 'Lithuania' 'Luxembourg'
 'MS Zaandam' 'Madagascar' 'Maldives' 'Mali' 'Malta' 'Mauritania'
 'Mauritius' 'Mexico' 'Moldova' 'Monaco' 'Mongolia' 'Montenegro' 'Morocco'
 'Mozambique' 'Namibia' 'Nepal' 'New Zealand' 'Nicaragua' 'Niger'
 'Nigeria' 'North Macedonia' 'Norway' 'Oman' 'Pakistan' 'Panama'
 'Papua New Guinea' 'Paraguay' 'Peru' 'Philippines' 'Poland' 'Portugal'
 'Qatar' 'Romania' 'Russia' 'Rwanda' 'Saint Kitts and Nevis' 'Saint Lucia'
 'Saint Vincent and the Grenadines' 'Samoa' 'San Marino' 'Saudi Arabia'
 'Senegal' 'Serbia' 'Seychelles' 'Sierra Leone' 'Singapore' 'Slovakia'
 'Slovenia' 'Somalia' 'South Africa' 'Spain' 'Sri Lanka' 'Sudan'
 'Suriname' 'Sweden' 'Switzerland' 'Syria' 'Taiwan*' 'Tanzania' 'Thailand'
 'Timor-Leste' 'Togo' 'Trinidad and Tobago' 'Tunisia' 'Turkey' 'Uganda'
 'Ukraine' 'United Arab Emirates' 'Uruguay' 'Uzbekistan' 'Venezuela'
 'Vietnam' 'West Bank and Gaza' 'Zambia' 'Zimbabwe' 'Kiribati' 'Palau'
 'Summer Olympics 2020' 'Malaysia' 'Tonga' 'Winter Olympics 2022'
 'Antarctica' 'Korea, North' 'Nauru' 'Tuvalu'] 190

In [13]:
countries.value_counts() # 해당 데이터는 미국 중심으로 되어 있구나!

Country_Region
US                2228
China               34
United Kingdom      18
Malaysia            17
Canada              16
                  ...
Ghana                1
Greece               1
Grenada              1
Guatemala            1
Tuvalu               1
Name: count, Length: 190, dtype: int64

In [ ]:
# 해당 데이터는 미국 주도 하에, 미국이 거의 90%에 해당하는 데이터의 지분율을 갖고 있구나!
# 국가별 발병을 보고 싶었으니까 --> 국가 정체 확인된 상태!!!
# 발병된 관련된 주요 데이터가 취합이 되어야 한다! 
# 국가 + 발병 관련 컬럼 정리 => 확진, 사망, 회복
# 특정 기준 값을 딱 잡고 특정 기준에 맞는 값을 붙여나가는 거야!

In [14]:
covid_stat = doc[["Confirmed", "Deaths", "Recovered"]]
covid_stat.head()

   Confirmed  Deaths  Recovered
0          4       0          0
1         47       1          0
2          7       0          0
3        195       3          0
4          1       0          0

In [15]:
# CHAPTER 2로 넘어간다!
# 미국 국가에 한해서 데이터 추출!
# 국가 별 이니까, 국가에 대한 부분을 먼저 보려고 해!

import pandas as pd

PATH = "COVID-19-master\csse_covid_19_data\csse_covid_19_daily_reports/"

doc = pd.read_csv(f"{PATH}04-01-2020.csv", encoding="utf-8-sig")

In [19]:
doc_us = doc[doc["Country_Region"] == "US"]

In [20]:
doc_us

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
0,45001.0,Abbeville,South Carolina,US,2020-04-01 21:58:49,34.223334,-82.461707,4,0,0,4,"Abbeville, South Carolina, US"
1,22001.0,Acadia,Louisiana,US,2020-04-01 21:58:49,30.295065,-92.414197,47,1,0,46,"Acadia, Louisiana, US"
2,51001.0,Accomack,Virginia,US,2020-04-01 21:58:49,37.767072,-75.632346,7,0,0,7,"Accomack, Virginia, US"
3,16001.0,Ada,Idaho,US,2020-04-01 21:58:49,43.452658,-116.241552,195,3,0,192,"Ada, Idaho, US"
4,19001.0,Adair,Iowa,US,2020-04-01 21:58:49,41.330756,-94.471059,1,0,0,1,"Adair, Iowa, US"
...,...,...,...,...,...,...,...,...,...,...,...,...
2246,66000.0,NaN,Guam,US,2020-04-01 21:58:49,13.444300,144.793700,77,3,0,74,"Guam, US"
2273,NaN,NaN,Northern Mariana Islands,US,2020-04-01 21:58:49,15.097900,145.673900,2,0,0,2,",Northern Mariana Islands,US"
2280,NaN,NaN,Puerto Rico,US,2020-04-01 21:58:49,18.220800,-66.590100,286,11,0,275,"Puerto Rico, US"
2285,NaN,NaN,Recovered,US,2020-04-01 21:58:49,0.000000,0.000000,0,0,8474,0,"Recovered, US"
2303,NaN,NaN,Virgin Islands,US,2020-04-01 21:58:49,18.335800,-64.896300,30,0,0,30,",Virgin Islands,US"

In [22]:
# CHAPTER 3 간다!
# CAHPTER 1 : 필요로 하는 컬럼만 찾아오는 방법
# CHAPTER 2 : 특정 국가만 조회하는 방법
# CHAPTER 3 : 결측이 발생했을 때 대처하는 방법

import pandas as pd

PATH = "COVID-19-master\csse_covid_19_data\csse_covid_19_daily_reports/"

doc = pd.read_csv(f"{PATH}01-22-2020.csv", encoding="utf-8-sig")

In [23]:
doc
# 같은 기관 똑같은 데이터 수집했지만, 수지한 시기에 따라 데이터 수집 형태가 다를 수 있구나!
# 데이터 수집 초반은 언제나 결측이 많음!

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,Anhui,Mainland China,1/22/2020 17:00,1.0,NaN,NaN
1,Beijing,Mainland China,1/22/2020 17:00,14.0,NaN,NaN
2,Chongqing,Mainland China,1/22/2020 17:00,6.0,NaN,NaN
3,Fujian,Mainland China,1/22/2020 17:00,1.0,NaN,NaN
4,Gansu,Mainland China,1/22/2020 17:00,NaN,NaN,NaN
...,...,...,...,...,...,...
71,Unknown,United Kingdom,1/22/2020 17:00,0.0,0.0,0.0
72,NaN,Nauru,1/22/2020 17:00,0.0,0.0,0.0
73,Niue,New Zealand,1/22/2020 17:00,0.0,0.0,0.0
74,NaN,Tuvalu,1/22/2020 17:00,0.0,0.0,0.0
75,Pitcairn Islands,United Kingdom,1/22/2020 17:00,0.0,0.0,0.0

In [25]:
doc.isnull().sum() # 결측치 확인 / 결측치 데이터 어떻게 처리하면 좋을까? 이걸 그냥 묻어두고 갈 수 없어

Province/State    12
Country/Region     0
Last Update        0
Confirmed         10
Deaths            37
Recovered         37
dtype: int64

In [ ]:
# 팀에서 결정해줘야 됨!
# 1) 결측치를 제거, 삭제를 하고 갈 것인가 (*전체 데이터 가운데 결측치가 차지하는 비율이 극소수일 경우)
# 2) 결측치 내부 값을 모두 0 혹인 빈문자 처리를 할 것인가 (* 향후 영산 등의 에러 발생률 감소 시킬 수는 있지만, 평균값 구할 때 오류 발생 가능성 커짐)
# 3) 결측치의 내부 값을 전체 데이터의 평균 혹은 중앙값으로 대체할 것인가 ( * 결측의 비율이 작지 않은 상태에서 향후 평균 등의 연산 처리 시, 왜곡된 데이터를 발생시키지 않고자 할 때)

In [28]:
# 1) 결측치 제거, 삭제
doc = doc.dropna() # not availabe 
doc.head()

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
13,Hubei,Mainland China,1/22/2020 17:00,444.0,17.0,28.0
41,Cook Islands,New Zealand,1/22/2020 17:00,0.0,0.0,0.0
43,Johor,Malaysia,1/22/2020 17:00,0.0,0.0,0.0
44,Kedah,Malaysia,1/22/2020 17:00,0.0,0.0,0.0
45,Kelantan,Malaysia,1/22/2020 17:00,0.0,0.0,0.0

In [29]:
doc.isnull().sum()

Province/State    0
Country/Region    0
Last Update       0
Confirmed         0
Deaths            0
Recovered         0
dtype: int64

In [ ]:
# 결측치의 데이터라고 해서 다 같은 비중을 차지하는 결측치는 아니다!
# A 컬럼에서의 결측, B 컬럼에서의 결측이 --> 가지고 있는 가치와 비중은 다를 수 있음!

In [30]:
import pandas as pd

PATH = "COVID-19-master\csse_covid_19_data\csse_covid_19_daily_reports/"

doc = pd.read_csv(f"{PATH}01-22-2020.csv", encoding="utf-8-sig")

In [31]:
doc.head()

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,Anhui,Mainland China,1/22/2020 17:00,1.0,NaN,NaN
1,Beijing,Mainland China,1/22/2020 17:00,14.0,NaN,NaN
2,Chongqing,Mainland China,1/22/2020 17:00,6.0,NaN,NaN
3,Fujian,Mainland China,1/22/2020 17:00,1.0,NaN,NaN
4,Gansu,Mainland China,1/22/2020 17:00,NaN,NaN,NaN

In [44]:
# 특정 컬럼의 결측치만 제거하고자 할 때
doc.dropna(subset=["Confirmed"])
doc.head()

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,Anhui,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
1,Beijing,Mainland China,1/22/2020 17:00,14.0,0.0,0.0
2,Chongqing,Mainland China,1/22/2020 17:00,6.0,0.0,0.0
3,Fujian,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
4,Gansu,Mainland China,1/22/2020 17:00,0.0,0.0,0.0

In [45]:
doc.isnull().sum()

Province/State    0
Country/Region    0
Last Update       0
Confirmed         0
Deaths            0
Recovered         0
dtype: int64

In [46]:
import pandas as pd

PATH = "COVID-19-master\csse_covid_19_data\csse_covid_19_daily_reports/"

doc = pd.read_csv(f"{PATH}01-22-2020.csv", encoding="utf-8-sig")

In [47]:
doc.isnull().sum()

Province/State    12
Country/Region     0
Last Update        0
Confirmed         10
Deaths            37
Recovered         37
dtype: int64

In [49]:
doc = doc.fillna(0)
doc.isnull().sum()

Province/State    0
Country/Region    0
Last Update       0
Confirmed         0
Deaths            0
Recovered         0
dtype: int64

In [50]:
doc.shape

(76, 6)

In [51]:
doc.head()

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,Anhui,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
1,Beijing,Mainland China,1/22/2020 17:00,14.0,0.0,0.0
2,Chongqing,Mainland China,1/22/2020 17:00,6.0,0.0,0.0
3,Fujian,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
4,Gansu,Mainland China,1/22/2020 17:00,0.0,0.0,0.0

In [53]:
doc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76 entries, 0 to 75
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Province/State  76 non-null     object
 1   Country/Region  76 non-null     object
 2   Last Update     76 non-null     object
 3   Confirmed       76 non-null     float64
 4   Deaths          76 non-null     float64
 5   Recovered       76 non-null     float64
dtypes: float64(3), object(3)
memory usage: 3.7+ KB

In [54]:
import pandas as pd

PATH = "COVID-19-master\csse_covid_19_data\csse_covid_19_daily_reports/"

doc = pd.read_csv(f"{PATH}01-22-2020.csv", encoding="utf-8-sig")

In [55]:
doc.isnull().sum()

Province/State    12
Country/Region     0
Last Update        0
Confirmed         10
Deaths            37
Recovered         37
dtype: int64

In [56]:
# 특정 컬럼 찾아와서, 그 컬럼에 특정 값을 주고 싶어!
nan_data = {"Deaths": 0, "Recovered": 0}
doc = doc.fillna(nan_data)
doc.isnull().sum()

Province/State    12
Country/Region     0
Last Update        0
Confirmed         10
Deaths             0
Recovered          0
dtype: int64