In [ ]:
지금부터 탐색적 데이터 분석 과정에 들어갑니다!
# 탐색적 데이터 분석 과정 = EDA = Exploratory Data Analysis
# 1) 데이터 출처 & 주제에 대한 이해 (확인 완료)
# 2) 데이터 크기 확인
# 3) 데이터 구성 요소 (각 컬럼 및 행 값) = featrue 특징 (최대, 최소, 평균, 중앙, 4분위, 이상치 등) 확인

# 데이터 확인하는 순서 및 방법은 다음과 같은 흐름으로! 시작!!!!

In [3]:
import pandas as pd

# Unicode => a = 1001, b = 1002 => utf-8-sig
doc = pd.read_csv("COVID-19-master\csse_covid_19_data\csse_covid_19_daily_reports/04-01-2020.csv", encoding="utf-8-sig")

In [4]:
doc

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
0,45001.0,Abbeville,South Carolina,US,2020-04-01 21:58:49,34.223334,-82.461707,4,0,0,4,"Abbeville, South Carolina, US"
1,22001.0,Acadia,Louisiana,US,2020-04-01 21:58:49,30.295065,-92.414197,47,1,0,46,"Acadia, Louisiana, US"
2,51001.0,Accomack,Virginia,US,2020-04-01 21:58:49,37.767072,-75.632346,7,0,0,7,"Accomack, Virginia, US"
3,16001.0,Ada,Idaho,US,2020-04-01 21:58:49,43.452658,-116.241552,195,3,0,192,"Ada, Idaho, US"
4,19001.0,Adair,Iowa,US,2020-04-01 21:58:49,41.330756,-94.471059,1,0,0,1,"Adair, Iowa, US"
...,...,...,...,...,...,...,...,...,...,...,...,...
2517,82604.0,NaN,Wales,United Kingdom,2020-04-01 21:58:49,52.130700,-3.783700,0,198,0,0,"Wales, United Kingdom"
2518,NaN,NaN,NaN,Nauru,2020-04-01 21:58:49,-0.522800,166.931500,0,0,0,0,Nauru
2519,NaN,NaN,Niue,New Zealand,2020-04-01 21:58:49,-19.054400,-169.867200,0,0,0,0,"Niue, New Zealand"
2520,NaN,NaN,NaN,Tuvalu,2020-04-01 21:58:49,-7.109500,177.649300,0,0,0,0,Tuvalu
2521,NaN,NaN,Pitcairn Islands,United Kingdom,2020-04-01 21:58:49,-24.376800,-128.324200,0,0,0,0,"Pitcairn Islands, United Kingdom"

In [5]:
doc.head()

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
0,45001.0,Abbeville,South Carolina,US,2020-04-01 21:58:49,34.223334,-82.461707,4,0,0,4,"Abbeville, South Carolina, US"
1,22001.0,Acadia,Louisiana,US,2020-04-01 21:58:49,30.295065,-92.414197,47,1,0,46,"Acadia, Louisiana, US"
2,51001.0,Accomack,Virginia,US,2020-04-01 21:58:49,37.767072,-75.632346,7,0,0,7,"Accomack, Virginia, US"
3,16001.0,Ada,Idaho,US,2020-04-01 21:58:49,43.452658,-116.241552,195,3,0,192,"Ada, Idaho, US"
4,19001.0,Adair,Iowa,US,2020-04-01 21:58:49,41.330756,-94.471059,1,0,0,1,"Adair, Iowa, US"

In [6]:
doc.head(10)

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
0,45001.0,Abbeville,South Carolina,US,2020-04-01 21:58:49,34.223334,-82.461707,4,0,0,4,"Abbeville, South Carolina, US"
1,22001.0,Acadia,Louisiana,US,2020-04-01 21:58:49,30.295065,-92.414197,47,1,0,46,"Acadia, Louisiana, US"
2,51001.0,Accomack,Virginia,US,2020-04-01 21:58:49,37.767072,-75.632346,7,0,0,7,"Accomack, Virginia, US"
3,16001.0,Ada,Idaho,US,2020-04-01 21:58:49,43.452658,-116.241552,195,3,0,192,"Ada, Idaho, US"
4,19001.0,Adair,Iowa,US,2020-04-01 21:58:49,41.330756,-94.471059,1,0,0,1,"Adair, Iowa, US"
5,29001.0,Adair,Missouri,US,2020-04-01 21:58:49,40.190586,-92.600782,3,0,0,3,"Adair, Missouri, US"
6,40001.0,Adair,Oklahoma,US,2020-04-01 21:58:49,35.884942,-94.658593,8,0,0,8,"Adair, Oklahoma, US"
7,8001.0,Adams,Colorado,US,2020-04-01 21:58:49,39.874321,-104.336258,623,47,0,179,"Adams, Colorado, US"
8,17001.0,Adams,Illinois,US,2020-04-01 21:58:49,39.988156,-91.187868,2,0,0,2,"Adams, Illinois, US"
9,18001.0,Adams,Indiana,US,2020-04-01 21:58:49,40.745765,-84.936714,1,0,0,1,"Adams, Indiana, US"

In [7]:
doc.tail()

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
2517,82604.0,NaN,Wales,United Kingdom,2020-04-01 21:58:49,52.1307,-3.7837,0,198,0,0,"Wales, United Kingdom"
2518,NaN,NaN,NaN,Nauru,2020-04-01 21:58:49,-0.5228,166.9315,0,0,0,0,Nauru
2519,NaN,NaN,Niue,New Zealand,2020-04-01 21:58:49,-19.0544,-169.8672,0,0,0,0,"Niue, New Zealand"
2520,NaN,NaN,NaN,Tuvalu,2020-04-01 21:58:49,-7.1095,177.6493,0,0,0,0,Tuvalu
2521,NaN,NaN,Pitcairn Islands,United Kingdom,2020-04-01 21:58:49,-24.3768,-128.3242,0,0,0,0,"Pitcairn Islands, United Kingdom"

In [8]:
doc.tail(10)

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
2512,NaN,NaN,NaN,"Korea, North",2020-04-01 21:58:49,40.3399,127.5101,0,0,0,0,"Korea, North"
2513,NaN,NaN,Unknown,Ukraine,2020-04-01 21:58:49,NaN,NaN,0,0,0,0,"Unknown, Ukraine"
2514,82601.0,NaN,England,United Kingdom,2020-04-01 21:58:49,52.3555,-1.1743,0,5430,0,0,"England, United Kingdom"
2515,82602.0,NaN,Northern Ireland,United Kingdom,2020-04-01 21:58:49,54.7877,-6.4923,0,59,0,0,"Northern Ireland, United Kingdom"
2516,82603.0,NaN,Scotland,United Kingdom,2020-04-01 21:58:49,56.4907,-4.2026,0,362,0,0,"Scotland, United Kingdom"
2517,82604.0,NaN,Wales,United Kingdom,2020-04-01 21:58:49,52.1307,-3.7837,0,198,0,0,"Wales, United Kingdom"
2518,NaN,NaN,NaN,Nauru,2020-04-01 21:58:49,-0.5228,166.9315,0,0,0,0,Nauru
2519,NaN,NaN,Niue,New Zealand,2020-04-01 21:58:49,-19.0544,-169.8672,0,0,0,0,"Niue, New Zealand"
2520,NaN,NaN,NaN,Tuvalu,2020-04-01 21:58:49,-7.1095,177.6493,0,0,0,0,Tuvalu
2521,NaN,NaN,Pitcairn Islands,United Kingdom,2020-04-01 21:58:49,-24.3768,-128.3242,0,0,0,0,"Pitcairn Islands, United Kingdom"

In [9]:
doc.shape # 2522 행의 12 열로 구성되어 있다! # 데이터 신뢰도! 너무 적으면 이 데이터를 가지고 분석할 만한 가치가 있을까?
# 이 안에 있는 데이터가 어떠한 타입으로 구성되어 있을까? 결측치는 얼마나 많을까? 세부적으로 들어가자!

(2522, 12)

In [10]:
doc.info() # 데이터 명세서
# FIPS 결측이 많이 나와 있네, 실수형 자료
# 감염자수나 등등은 결측이 없네
# 이런 것들 확인!!!

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2522 entries, 0 to 2521
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   FIPS            2175 non-null   float64
 1   Admin2          2221 non-null   object
 2   Province_State  2338 non-null   object
 3   Country_Region  2522 non-null   object
 4   Last_Update     2522 non-null   object
 5   Lat             2518 non-null   float64
 6   Long_           2518 non-null   float64
 7   Confirmed       2522 non-null   int64
 8   Deaths          2522 non-null   int64
 9   Recovered       2522 non-null   int64
 10  Active          2522 non-null   int64
 11  Combined_Key    2522 non-null   object
dtypes: float64(3), int64(4), object(5)
memory usage: 236.6+ KB

In [11]:
doc.columns # 이러한 열들로 구성되어 있구나! 이러한 값들을 수집했네!

Index(['FIPS', 'Admin2', 'Province_State', 'Country_Region', 'Last_Update',
       'Lat', 'Long_', 'Confirmed', 'Deaths', 'Recovered', 'Active',
       'Combined_Key'],
      dtype='object')

In [13]:
doc.describe() # 좀 더 세부적인 갓들을 보고 싶어!
# 전체 데이터를 중요한 지표만 추출해서 묘사한 것! 
# count : 행 수 / mean : 평균값 / std : 표준편차(평균으로부터 얼마나 떨어져 있는가에 대한 평균값) / min : 최소값 / max : 최대값
# 5 number summary
# FIPS는 왜 유독 없을까? FIPS = Federal Information Processing Standards Code = 미국 연방 지역 식별 코드 = 미국의 각각의 주, 도시의 식별값
# FIPS => Ex. 36061 : 뉴욕시 맨해튼 / 06037 : 미국 로스앤젤레스

# 데이터 수집해서 분석을 할 때 --> 높은 확률로 상관관계를 따지기 원해! 연결고리를 보려고 하는 것!
# 현재 우리의 데이터가 상관관계를 따져볼 수 있는 포맷(타입)으로 구성되어 있는가? --> 수학 공식을 통해 상관관계를 따짐! --> 모든 값들이 수치화된, 정형화된 값이 되어야 함!
# 보통은 이것이 쉽지 않아. 보려고 하는 것이 정형화된 데이터이기 쉽지 않아!

,FIPS,Lat,Long_,Confirmed,Deaths,Recovered,Active
count,2175.000000,2518.000000,2518.000000,2522.000000,2522.000000,2522.000000,2522.000000
mean,30114.640920,35.289228,-75.615792,372.307296,20.477002,76.656622,278.524187
std,15643.080021,12.149460,47.809329,4174.952692,363.948042,1494.960160,2945.050096
min,1001.000000,-71.949900,-175.198200,0.000000,0.000000,0.000000,0.000000
25%,18052.000000,33.086811,-94.749118,2.000000,0.000000,0.000000,2.000000
50%,29031.000000,37.526763,-86.065254,7.000000,0.000000,0.000000,6.000000
75%,45024.000000,41.406878,-79.042655,34.000000,1.000000,0.000000,31.000000
max,99999.000000,71.706900,178.065000,110574.000000,13155.000000,63326.000000,80572.000000

In [16]:
# doc.corr() ---> doc에 문자열이 들어있기 때문에 error 가 날 거야!
# 문자열이 아닌 수치화된 데이터만 가져와서 상관관계를 따져보고 싶은 거야!
# 그럴 때 인자값으로 숫자만 갖고 오게 해야 됨!

doc.corr(numeric_only=True)
# 코로나 확진 판정 받으면 죽을 위험이 0.837153 : 상관관계가 높은 편
# 사망 확률도 높았지만, 회복할 수 있는 확률도 높았기 때문에 그래도 희망이 있다! 관리만 잘하면 회복이 가능한 병
# 확진 판정 받았으나 증상이 없는 사람도 있었다 물론 그 수는 매우 작았지만
# 이런 식으로 대략 판단! 디테일하게 판단 하려면 세부적으로 가야겠지!

,FIPS,Lat,Long_,Confirmed,Deaths,Recovered,Active
FIPS,1.000000,0.160717,0.171490,-0.000504,0.076467,NaN,0.002718
Lat,0.160717,1.000000,-0.476426,0.029389,0.026309,-0.002781,0.035631
Long_,0.171490,-0.476426,1.000000,0.141126,0.096924,0.141932,0.119737
Confirmed,-0.000504,0.029389,0.141126,1.000000,0.837153,0.727305,0.942484
Deaths,0.076467,0.026309,0.096924,0.837153,1.000000,0.546858,0.796549
Recovered,NaN,-0.002781,0.141932,0.727305,0.546858,1.000000,0.462484
Active,0.002718,0.035631,0.119737,0.942484,0.796549,0.462484,1.000000